### ISSUE TITLE
taskwarrior discord server invitation!

### ISSUE THREAD

**Issue by linuxcaffe** [rmonico/itask#5]
Did you know that there's an itask channel on the taskwarrior discord server?? Probably not..
Join us for some lively chat; https://discord.gg/n4K3zBYJJs

**Comment by rmonicovia** [comment]
Thanks a lot! I seeing this just now. Im closing the issue.

**Comment by rmonico** [comment]
Thanks a lot! I seeing this just now. Im closing the issue.
